uvdesk_community_installation_wizard:
    path:     /setup/
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizard::wizard

uvdesk_community_installation_wizard_locale:
    path:     /setup/{_locale}/
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizard::wizard