uvdesk_community_installation_wizard:
    path:     /setup/
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizard::loadWizard

uvdesk_community_installation_wizard_locale:
    path:     /setup/{_locale}/
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizard::loadWizard

uvdesk_community_installation_wizard_check_requirements:
    path:     /setup/xhr/check-requirements
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::evaluateSystemRequirements
    methods: [POST]

uvdesk_community_installation_wizard_verify_database_credentials:
    path:     /setup/xhr/verify-database-credentials
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::verifyDatabaseCredentials
    methods: [POST]

uvdesk_community_installation_wizard_store_super_user_credentials:
    path:     /setup/xhr/intermediary/super-user
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::prepareSuperUserDetailsXHR
    methods: [POST]

udvesk_community_installation_wizard_update_website_configuration:
    path: /setup/xhr/load/website-configure
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::setWebsiteConfigurationXHR
    methods: [POST]

udvesk_community_installation_wizard_website_configuration:
    path: /setup/xhr/load/website-prefixes
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::getWebsiteConfigurationXHR
    methods: [GET]

uvdesk_community_installation_wizard_update_configurations_xhr:
    path:     /setup/xhr/load/configurations
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::updateConfigurationsXHR
    methods: [POST]

uvdesk_community_installation_wizard_migrate_database_schema_xhr:
    path:     /setup/xhr/load/migrations
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::migrateDatabaseSchemaXHR
    methods: [POST]

uvdesk_community_installation_wizard_populate_database_entities_xhr:
    path:     /setup/xhr/load/entities
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::populateDatabaseEntitiesXHR
    methods: [POST]

uvdesk_community_installation_wizard_create_default_super_user_xhr:
    path:     /setup/xhr/load/super-user
    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::createDefaultSuperUserXHR
    methods: [POST]

